drop table if exists Product_order;
drop table if exists orders;
drop table if exists Products;
create table if not exists Products (id serial primary key, title varchar(250), description text, price integer);
create table if not exists Orders (id serial primary key, number integer, date date);
create table if not exists Product_Order (id serial primary key, orderId integer REFERENCES Orders(id) on delete cascade, productId integer REFERENCES Products(id) on delete cascade, amount integer);
insert into Products (title, description, price) values ('конструктор', 'игрушка детская пластик', 250);
insert into Products (title, description, price) values ('Мишка плюшевый', 'игрушка детская мягкая', 500);
insert into Products (title, description, price) values ('Кукла Маша', 'игрушка детская', 680);
insert into Orders (number, date) VALUES (1254,'2023/10/05');
insert into Orders (number, date) VALUES (2685,'2023/11/08');
insert into Orders (number, date) VALUES (3564,'2023/12/01');
insert into Product_Order (orderId, productId,amount) VALUES (1,1,2);
insert into Product_Order (orderId, productId,amount) VALUES (1,2,3);
insert into Product_Order (orderId, productId,amount) VALUES (1,3,1);
insert into Product_Order (orderId, productId,amount) VALUES (2,2,1);
insert into Product_Order (orderId, productId,amount) VALUES (2,3,2);
insert into Product_Order (orderId, productId,amount) VALUES (3,3,1);
insert into Product_Order (orderId, productId,amount) VALUES (3,2,2);
SELECT *from Products;
select date, title, amount, description,price from product_order join Orders O on O.id = product_order.orderId join Products P on P.id = product_order.productId where number =1254;
select number from product_order join Orders O on O.id = product_order.orderId join Products P on P.id = product_order.productId group by number having sum(price*amount)<=5000;
select number from product_order join Orders O on O.id = product_order.orderId join Products P on P.id = product_order.productId group by number having sum(amount)=6;
select number from product_order join Orders O on O.id = product_order.orderId join Products P on P.id = product_order.productId where title ='Кукла Маша' group by number;